#!/usr/bin/python
import sys
sys.path.extend(['/var/www/lib/python','/var/www/html/dwiki'])
from LocalWiki import wikiutil,config
import cPickle
from popen2 import popen2
import os

def write_id(pagename,id):
        """
        write the id of the page (new page) to the file (search index stuff)
        """
	if os.path.exists(config.app_dir + '/index_id.pickle'):
        	idfile = open(config.app_dir +'/index_id.pickle' , 'r') # pickled pagedict
        	iddict =  cPickle.load(idfile)
        	idfile.close()
		iddict[pagename] = id	
	else:
		iddict = {}

	idfile = open(config.app_dir + '/index_id.pickle', 'w')
	cPickle.dump(iddict, idfile, 2)
	idfile.close()

def lookup_id(pagename):
        """
        lookup the id of the page in the table (for search index stuff)
        """
	if os.path.exists(config.app_dir + '/index_id.pickle'):
        	idfile = open(config.app_dir +"/index_id.pickle","r")
		iddict = cPickle.load(idfile)
		if iddict.has_key(pagename):
			return iddict[pagename]
		else:
        		return 0
	else:
		return 0

if len(sys.argv) < 3:
	print "need pagename and pagetext"
	sys.exit(1)

pagename = sys.argv[1]
pagetext = sys.argv[2]

if len(sys.argv) == 5:
	search_db = sys.argv[3]
	title_search_db = sys.argv[4]
	extras = True
else:
	extras = False

pagetext = wikiutil.unquoteFilename(pagetext)

id = lookup_id(pagename)
if not extras:
	output, input = popen2(config.app_dir + "/index_page" + " " + config.app_dir + "/search_db %s %s" % (id, pagename))
else:
	output, input = popen2(config.app_dir + "/index_page" + " " + config.app_dir + "/%s %s %s" % (search_db, id, pagename))	

input.write(pagetext + '\n')
input.close()
new_id = (output.readline()).strip('\n')
output.close()

if new_id:
	write_id(pagename,new_id)

# write to the title index as well
if not extras:
	output, input = popen2(config.app_dir + "/index_page" + " " + config.app_dir + "/title_search_db %s %s" % (lookup_id(pagename), pagename))
else:
        output, input = popen2(config.app_dir + "/index_page" + " " + config.app_dir + "/%s %s %s" % (title_search_db, lookup_id(pagename), pagename))

input.write(wikiutil.unquoteWikiname(pagename) + '\n')
input.close()
output.close()
