#!/usr/bin/python
import sys
sys.path.extend(['/home/dwiki/lib/python','/home/dwiki/public_html/dwiki'])
from LocalWiki import wikiutil
from popen2 import popen2

def write_id(pagename,id):
        """
        write the id of the page (new page) to the file (search index stuff)
        """
        id_file = open("/home/dwiki/index_id_file","a")
        id_file.write(pagename + "\n")
        id_file.write(id + "\n")
        id_file.close()

def lookup_id(pagename):
        """
        lookup the id of the page in the table (for search index stuff)
        """
        id_file = open("/home/dwiki/index_id_file","r")
        name = id_file.readline()
        while (name):
           id = id_file.readline()
           if name == (pagename + "\n"):
                id_file.close() 
                return int(id)
           name = id_file.readline()
                
        id_file.close()
        return 0

if len(sys.argv) != 3:
	print "need pagename and pagetext"
	sys.exit(1)

pagename = sys.argv[1]
pagetext = sys.argv[2]
pagetext = wikiutil.unquoteFilename(pagetext)

id = lookup_id(pagename)
output, input = popen2("/home/dwiki/index_page /home/dwiki/search_db %s %s" % (id, pagename))
input.write(pagetext + '\n')
input.close()
new_id = (output.readline()).strip('\n')
output.close()
if new_id:
	write_id(pagename,new_id)
# write to the title index as well
output, input = popen2("/home/dwiki/index_page /home/dwiki/title_search_db %s %s" % (lookup_id(pagename), pagename))
input.write(wikiutil.unquoteWikiname(pagename) + '\n')
input.close()
output.close()
