#!/usr/bin/python
import sys
sys.path.extend(['/Library/Webserver','/Library/Webserver/Documents/installhtml/dwiki'])
from LocalWiki import wikiutil,config
from popen2 import popen2
import cPickle, os

def process_id(pagename, id_list):
        """
        lookup the id of the page in the table (for search index stuff)
	and delete the id from the index
        """
        idfile = open(config.app_dir +'/index_id.pickle' , 'r') # pickled pagedict
        iddict =  cPickle.load(idfile)
        idfile.close()
	
	if iddict.has_key(pagename):
		id = iddict[pagename]
		del iddict[pagename]
		idfile = open(config.app_dir +'/index_id.pickle', 'w')
		cPickle.dump(iddict, idfile, 2)
		idfile.close()
		return id
	else:
		# this shouldn't happen
		return 0


if len(sys.argv) != 2:
	print "need pagename"
	sys.exit(1)

pagename = sys.argv[1]

id_file = open(config.app_dir + "/index_id_file", "r")
id_list = id_file.readlines()

id = process_id(pagename, id_list)

os.spawnl(os.P_NOWAIT, config.app_dir + '/remove_page', config.app_dir + '/remove_page', config.app_dir + '/search_db', str(id))
os.spawnl(os.P_NOWAIT, config.app_dir + '/remove_page', config.app_dir + '/remove_page', config.app_dir + '/title_search_db', str(id))
